// Variable name is 'city_database' (snake_case) to match the variable used in pro_version.html
const city_database = [
  { city: "Adelaide", country: "Australia", code: "SA", timezone: "Australia/Adelaide" },
  { city: "Albany", country: "Australia", code: "WA", timezone: "Australia/Perth" },
  { city: "Alice Springs", country: "Australia", code: "NT", timezone: "Australia/Darwin" },
  { city: "Amsterdam", country: "Netherlands", code: "NH", timezone: "Europe/Amsterdam" },
  { city: "Athens", country: "Greece", code: "I", timezone: "Europe/Athens" },
  { city: "Atlanta", country: "USA", code: "GA", timezone: "America/New_York" },
  { city: "Auckland", country: "New Zealand", code: "AUK", timezone: "Pacific/Auckland" },
  { city: "Austin", country: "USA", code: "TX", timezone: "America/Chicago" },
  { city: "Ballarat", country: "Australia", code: "VIC", timezone: "Australia/Melbourne" },
  { city: "Bangkok", country: "Thailand", code: "10", timezone: "Asia/Bangkok" },
  { city: "Barcelona", country: "Spain", code: "CT", timezone: "Europe/Madrid" },
  { city: "Beijing", country: "China", code: "11", timezone: "Asia/Shanghai" },
  { city: "Bendigo", country: "Australia", code: "VIC", timezone: "Australia/Melbourne" },
  { city: "Berlin", country: "Germany", code: "BE", timezone: "Europe/Berlin" },
  { city: "Boston", country: "USA", code: "MA", timezone: "America/New_York" },
  { city: "Brasília", country: "Brazil", code: "DF", timezone: "America/Sao_Paulo" },
  { city: "Brisbane", country: "Australia", code: "QLD", timezone: "Australia/Brisbane" },
  { city: "Broome", country: "Australia", code: "WA", timezone: "Australia/Perth" },
  { city: "Brussels", country: "Belgium", code: "BRU", timezone: "Europe/Brussels" },
  { city: "Bucharest", country: "Romania", code: "B", timezone: "Europe/Bucharest" },
  { city: "Budapest", country: "Hungary", code: "BU", timezone: "Europe/Budapest" },
  { city: "Buenos Aires", country: "Argentina", code: "C", timezone: "America/Argentina/Buenos_Aires" },
  { city: "Bunbury", country: "Australia", code: "WA", timezone: "Australia/Perth" },
  { city: "Bundaberg", country: "Australia", code: "QLD", timezone: "Australia/Brisbane" },
  { city: "Burnie", country: "Australia", code: "TAS", timezone: "Australia/Hobart" },
  { city: "Byron Bay", country: "Australia", code: "NSW", timezone: "Australia/Sydney" },
  { city: "Cairo", country: "Egypt", code: "C", timezone: "Africa/Cairo" },
  { city: "Cairns", country: "Australia", code: "QLD", timezone: "Australia/Brisbane" },
  { city: "Calgary", country: "Canada", code: "AB", timezone: "America/Edmonton" },
  { city: "Canberra", country: "Australia", code: "ACT", timezone: "Australia/Sydney" },
  { city: "Cape Town", country: "South Africa", code: "WC", timezone: "Africa/Johannesburg" },
  { city: "Central Coast (Gosford)", country: "Australia", code: "NSW", timezone: "Australia/Sydney" },
  { city: "Chicago", country: "USA", code: "IL", timezone: "America/Chicago" },
  { city: "Coffs Harbour", country: "Australia", code: "NSW", timezone: "Australia/Sydney" },
  { city: "Copenhagen", country: "Denmark", code: "84", timezone: "Europe/Copenhagen" },
  { city: "Dallas", country: "USA", code: "TX", timezone: "America/Chicago" },
  { city: "Darwin", country: "Australia", code: "NT", timezone: "Australia/Darwin" },
  { city: "Denver", country: "USA", code: "CO", timezone: "America/Denver" },
  { city: "Devonport", country: "Australia", code: "TAS", timezone: "Australia/Hobart" },
  { city: "Dhaka", country: "Bangladesh", code: "C", timezone: "Asia/Dhaka" },
  { city: "Doha", country: "Qatar", code: "DA", timezone: "Asia/Qatar" },
  { city: "Dubai", country: "UAE", code: "DU", timezone: "Asia/Dubai" },
  { city: "Dublin", country: "Ireland", code: "D", timezone: "Europe/Dublin" },
  { city: "Edinburgh", country: "UK", code: "SCT", timezone: "Europe/London" },
  { city: "Frankfurt", country: "Germany", code: "HE", timezone: "Europe/Berlin" },
  { city: "Fremantle", country: "Australia", code: "WA", timezone: "Australia/Perth" },
  { city: "Geelong", country: "Australia", code: "VIC", timezone: "Australia/Melbourne" },
  { city: "Geneva", country: "Switzerland", code: "GE", timezone: "Europe/Zurich" },
  { city: "Gold Coast", country: "Australia", code: "QLD", timezone: "Australia/Brisbane" },
  { city: "Hanoi", country: "Vietnam", code: "HN", timezone: "Asia/Ho_Chi_Minh" },
  { city: "Helsinki", country: "Finland", code: "18", timezone: "Europe/Helsinki" },
  { city: "Hervey Bay", country: "Australia", code: "QLD", timezone: "Australia/Brisbane" },
  { city: "Hobart", country: "Australia", code: "TAS", timezone: "Australia/Hobart" },
  { city: "Hong Kong", country: "China", code: "HK", timezone: "Asia/Hong_Kong" },
  { city: "Honolulu", country: "USA", code: "HI", timezone: "Pacific/Honolulu" },
  { city: "Houston", country: "USA", code: "TX", timezone: "America/Chicago" },
  { city: "Istanbul", country: "Turkey", code: "34", timezone: "Europe/Istanbul" },
  { city: "Jakarta", country: "Indonesia", code: "JK", timezone: "Asia/Jakarta" },
  { city: "Jerusalem", country: "Israel", code: "JM", timezone: "Asia/Jerusalem" },
  { city: "Johannesburg", country: "South Africa", code: "GP", timezone: "Africa/Johannesburg" },
  { city: "Karachi", country: "Pakistan", code: "SD", timezone: "Asia/Karachi" },
  { city: "Katherine", country: "Australia", code: "NT", timezone: "Australia/Darwin" },
  { city: "Kyiv", country: "Ukraine", code: "30", timezone: "Europe/Kiev" },
  { city: "Kuala Lumpur", country: "Malaysia", code: "14", timezone: "Asia/Kuala_Lumpur" },
  { city: "Lagos", country: "Nigeria", code: "LA", timezone: "Africa/Lagos" },
  { city: "Launceston", country: "Australia", code: "TAS", timezone: "Australia/Hobart" },
  { city: "Lima", country: "Peru", code: "LMA", timezone: "America/Lima" },
  { city: "Lisbon", country: "Portugal", code: "11", timezone: "Europe/Lisbon" },
  { city: "London", country: "UK", code: "ENG", timezone: "Europe/London" },
  { city: "Los Angeles", country: "USA", code: "CA", timezone: "America/Los_Angeles" },
  { city: "Mackay", country: "Australia", code: "QLD", timezone: "Australia/Brisbane" },
  { city: "Madrid", country: "Spain", code: "MD", timezone: "Europe/Madrid" },
  { city: "Manchester", country: "UK", code: "ENG", timezone: "Europe/London" },
  { city: "Mandurah", country: "Australia", code: "WA", timezone: "Australia/Perth" },
  { city: "Manila", country: "Philippines", code: "00", timezone: "Asia/Manila" },
  { city: "Melbourne", country: "Australia", code: "VIC", timezone: "Australia/Melbourne" },
  { city: "Mexico City", country: "Mexico", code: "CMX", timezone: "America/Mexico_City" },
  { city: "Miami", country: "USA", code: "FL", timezone: "America/New_York" },
  { city: "Mildura", country: "Australia", code: "VIC", timezone: "Australia/Melbourne" },
  { city: "Montreal", country: "Canada", code: "QC", timezone: "America/Toronto" },
  { city: "Moscow", country: "Russia", code: "MOW", timezone: "Europe/Moscow" },
  { city: "Mount Gambier", country: "Australia", code: "SA", timezone: "Australia/Adelaide" },
  { city: "Mumbai", country: "India", code: "MH", timezone: "Asia/Kolkata" },
  { city: "Nairobi", country: "Kenya", code: "110", timezone: "Africa/Nairobi" },
  { city: "New Delhi", country: "India", code: "DL", timezone: "Asia/Kolkata" },
  { city: "New York", country: "USA", code: "NY", timezone: "America/New_York" },
  { city: "Newcastle", country: "Australia", code: "NSW", timezone: "Australia/Sydney" },
  { city: "Nhulunbuy", country: "Australia", code: "NT", timezone: "Australia/Darwin" },
  { city: "Oslo", country: "Norway", code: "03", timezone: "Europe/Oslo" },
  { city: "Ottawa", country: "Canada", code: "ON", timezone: "America/Toronto" },
  { city: "Palmerston", country: "Australia", code: "NT", timezone: "Australia/Darwin" },
  { city: "Paris", country: "France", code: "IDF", timezone: "Europe/Paris" },
  { city: "Perth", country: "Australia", code: "WA", timezone: "Australia/Perth" },
  { city: "Phoenix", country: "USA", code: "AZ", timezone: "America/Phoenix" },
  { city: "Port Augusta", country: "Australia", code: "SA", timezone: "Australia/Adelaide" },
  { city: "Port Lincoln", country: "Australia", code: "SA", timezone: "Australia/Adelaide" },
  { city: "Port Macquarie", country: "Australia", code: "NSW", timezone: "Australia/Sydney" },
  { city: "Port Pirie", country: "Australia", code: "SA", timezone: "Australia/Adelaide" },
  { city: "Prague", country: "Czechia", code: "10", timezone: "Europe/Prague" },
  { city: "Queenstown", country: "Australia", code: "TAS", timezone: "Australia/Hobart" },
  { city: "Reykjavik", country: "Iceland", code: "1", timezone: "Atlantic/Reykjavik" },
  { city: "Rio de Janeiro", country: "Brazil", code: "RJ", timezone: "America/Sao_Paulo" },
  { city: "Riyadh", country: "Saudi Arabia", code: "01", timezone: "Asia/Riyadh" },
  { city: "Rockhampton", country: "Australia", code: "QLD", timezone: "Australia/Brisbane" },
  { city: "Rome", country: "Italy", code: "62", timezone: "Europe/Rome" },
  { city: "San Francisco", country: "USA", code: "CA", timezone: "America/Los_Angeles" },
  { city: "Santiago", country: "Chile", code: "RM", timezone: "America/Santiago" },
  { city: "Sao Paulo", country: "Brazil", code: "SP", timezone: "America/Sao_Paulo" },
  { city: "Seattle", country: "USA", code: "WA", timezone: "America/Los_Angeles" },
  { city: "Seoul", country: "South Korea", code: "11", timezone: "Asia/Seoul" },
  { city: "Shanghai", country: "China", code: "31", timezone: "Asia/Shanghai" },
  { city: "Shepparton", country: "Australia", code: "VIC", timezone: "Australia/Melbourne" },
  { city: "Singapore", country: "Singapore", code: "01", timezone: "Asia/Singapore" },
  { city: "Stockholm", country: "Sweden", code: "AB", timezone: "Europe/Stockholm" },
  { city: "Sunshine Coast (Maroochydore)", country: "Australia", code: "QLD", timezone: "Australia/Brisbane" },
  { city: "Sydney", country: "Australia", code: "NSW", timezone: "Australia/Sydney" },
  { city: "Taipei", country: "Taiwan", code: "TPE", timezone: "Asia/Taipei" },
  { city: "Tamworth", country: "Australia", code: "NSW", timezone: "Australia/Sydney" },
  { city: "Tennant Creek", country: "Australia", code: "NT", timezone: "Australia/Darwin" },
  { city: "Tokyo", country: "Japan", code: "13", timezone: "Asia/Tokyo" },
  { city: "Toowoomba", country: "Australia", code: "QLD", timezone: "Australia/Brisbane" },
  { city: "Toronto", country: "Canada", code: "ON", timezone: "America/Toronto" },
  { city: "Townsville", country: "Australia", code: "QLD", timezone: "Australia/Brisbane" },
  { city: "Ulverstone", country: "Australia", code: "TAS", timezone: "Australia/Hobart" },
  { city: "Vancouver", country: "Canada", code: "BC", timezone: "America/Vancouver" },
  { city: "Vienna", country: "Austria", code: "9", timezone: "Europe/Vienna" },
  { city: "Wagga Wagga", country: "Australia", code: "NSW", timezone: "Australia/Sydney" },
  { city: "Warsaw", country: "Poland", code: "14", timezone: "Europe/Warsaw" },
  { city: "Washington D.C.", country: "USA", code: "DC", timezone: "America/New_York" },
  { city: "Wellington", country: "New Zealand", code: "WGN", timezone: "Pacific/Auckland" },
  { city: "Whyalla", country: "Australia", code: "SA", timezone: "Australia/Adelaide" },
  { city: "Wollongong", country: "Australia", code: "NSW", timezone: "Australia/Sydney" },
  { city: "Zurich", country: "Switzerland", code: "ZH", timezone: "Europe/Zurich" }
];
