// This is your external database of cities.
// To add a new city, just copy one of the lines, paste it at the end (before the last `];`),
// and change the details.

const cityDatabase = [
    // Your Mum's Requested Cities!
    { city: "Manchester", country: "UK", code: "MAN", timezone: "Europe/London" },
    { city: "Austin", country: "USA", code: "AUS", timezone: "America/Chicago" },
    { city: "Gold Coast (Surfers Paradise)", country: "Australia", code: "OOL", timezone: "Australia/Brisbane" },

    // North America
    { city: "New York", country: "USA", code: "JFK", timezone: "America/New_York" },
    { city: "Los Angeles", country: "USA", code: "LAX", timezone: "America/Los_Angeles" },
    { city: "Chicago", country: "USA", code: "ORD", timezone: "America/Chicago" },
    { city: "Houston", country: "USA", code: "IAH", timezone: "America/Chicago" },
    { city: "Phoenix", country: "USA", code: "PHX", timezone: "America/Phoenix" },
    { city: "Philadelphia", country: "USA", code: "PHL", timezone: "America/New_York" },
    { city: "San Antonio", country: "USA", code: "SAT", timezone: "America/Chicago" },
    { city: "San Diego", country: "USA", code: "SAN", timezone: "America/Los_Angeles" },
    { city: "Dallas", country: "USA", code: "DFW", timezone: "America/Chicago" },
    { city: "San Jose", country: "USA", code: "SJC", timezone: "America/Los_Angeles" },
    { city: "Jacksonville", country: "USA", code: "JAX", timezone: "America/New_York" },
    { city: "San Francisco", country: "USA", code: "SFO", timezone: "America/Los_Angeles" },
    { city: "Indianapolis", country: "USA", code: "IND", timezone: "America/Indiana/Indianapolis" },
    { city: "Columbus", country: "USA", code: "CMH", timezone: "America/New_York" },
    { city: "Charlotte", country: "USA", code: "CLT", timezone: "America/New_York" },
    { city: "Seattle", country: "USA", code: "SEA", timezone: "America/Los_Angeles" },
    { city: "Denver", country: "USA", code: "DEN", timezone: "America/Denver" },
    { city: "Washington D.C.", country: "USA", code: "IAD", timezone: "America/New_York" },
    { city: "Boston", country: "USA", code: "BOS", timezone: "America/New_York" },
    { city: "Detroit", country: "USA", code: "DTW", timezone: "America/Detroit" },
    { city: "Nashville", country: "USA", code: "BNA", timezone: "America/Chicago" },
    { city: "Memphis", country: "USA", code: "MEM", timezone: "America/Chicago" },
    { city: "Portland", country: "USA", code: "PDX", timezone: "America/Los_Angeles" },
    { city: "Las Vegas", country: "USA", code: "LAS", timezone: "America/Los_Angeles" },
    { city: "Miami", country: "USA", code: "MIA", timezone: "America/New_York" },
    { city: "Atlanta", country: "USA", code: "ATL", timezone: "America/New_York" },
    { city: "Toronto", country: "Canada", code: "YYZ", timezone: "America/Toronto" },
    { city: "Montreal", country: "Canada", code: "YUL", timezone: "America/Toronto" },
    { city: "Vancouver", country: "Canada", code: "YVR", timezone: "America/Vancouver" },
    { city: "Calgary", country: "Canada", code: "YYC", timezone: "America/Edmonton" },
    { city: "Ottawa", country: "Canada", code: "YOW", timezone: "America/Toronto" },
    { city: "Edmonton", country: "Canada", code: "YEG", timezone: "America/Edmonton" },
    { city: "Mexico City", country: "Mexico", code: "MEX", timezone: "America/Mexico_City" },
    { city: "Guadalajara", country: "Mexico", code: "GDL", timezone: "America/Mexico_City" },
    { city: "Monterrey", country: "Mexico", code: "MTY", timezone: "America/Monterrey" },

    // South America
    { city: "São Paulo", country: "Brazil", code: "GRU", timezone: "America/Sao_Paulo" },
    { city: "Rio de Janeiro", country: "Brazil", code: "GIG", timezone: "America/Sao_Paulo" },
    { city: "Buenos Aires", country: "Argentina", code: "EZE", timezone: "America/Argentina/Buenos_Aires" },
    { city: "Bogotá", country: "Colombia", code: "BOG", timezone: "America/Bogota" },
    { city: "Lima", country: "Peru", code: "LIM", timezone: "America/Lima" },
    { city: "Santiago", country: "Chile", code: "SCL", timezone: "America/Santiago" },
    { city: "Caracas", country: "Venezuela", code: "CCS", timezone: "America/Caracas" },

    // Europe
    { city: "London", country: "UK", code: "LHR", timezone: "Europe/London" },
    { city: "Birmingham", country: "UK", code: "BHX", timezone: "Europe/London" },
    { city: "Glasgow", country: "UK", code: "GLA", timezone: "Europe/London" },
    { city: "Dublin", country: "Ireland", code: "DUB", timezone: "Europe/Dublin" },
    { city: "Berlin", country: "Germany", code: "BER", timezone: "Europe/Berlin" },
    { city: "Hamburg", country: "Germany", code: "HAM", timezone: "Europe/Berlin" },
    { city: "Munich", country: "Germany", code: "MUC", timezone: "Europe/Berlin" },
    { city: "Frankfurt", country: "Germany", code: "FRA", timezone: "Europe/Berlin" },
    { city: "Cologne", country: "Germany", code: "CGN", timezone: "Europe/Berlin" },
    { city: "Madrid", country: "Spain", code: "MAD", timezone: "Europe/Madrid" },
    { city: "Barcelona", country: "Spain", code: "BCN", timezone: "Europe/Madrid" },
    { city: "Rome", country: "Italy", code: "FCO", timezone: "Europe/Rome" },
    { city: "Milan", country: "Italy", code: "MXP", timezone: "Europe/Rome" },
    { city: "Paris", country: "France", code: "CDG", timezone: "Europe/Paris" },
    { city: "Marseille", country: "France", code: "MRS", timezone: "Europe/Paris" },
    { city: "Lyon", country: "France", code: "LYS", timezone: "Europe/Paris" },
    { city: "Amsterdam", country: "Netherlands", code: "AMS", timezone: "Europe/Amsterdam" },
    { city: "Brussels", country: "Belgium", code: "BRU", timezone: "Europe/Brussels" },
    { city: "Vienna", country: "Austria", code: "VIE", timezone: "Europe/Vienna" },
    { city: "Zurich", country: "Switzerland", code: "ZRH", timezone: "Europe/Zurich" },
    { city: "Geneva", country: "Switzerland", code: "GVA", timezone: "Europe/Zurich" },
    { city: "Stockholm", country: "Sweden", code: "ARN", timezone: "Europe/Stockholm" },
    { city: "Oslo", country: "Norway", code: "OSL", timezone: "Europe/Oslo" },
    { city: "Copenhagen", country: "Denmark", code: "CPH", timezone: "Europe/Copenhagen" },
    { city: "Helsinki", country: "Finland", code: "HEL", timezone: "Europe/Helsinki" },
    { city: "Warsaw", country: "Poland", code: "WAW", timezone: "Europe/Warsaw" },
    { city: "Prague", country: "Czech Republic", code: "PRG", timezone: "Europe/Prague" },
    { city: "Budapest", country: "Hungary", code: "BUD", timezone: "Europe/Budapest" },
    { city: "Athens", country: "Greece", code: "ATH", timezone: "Europe/Athens" },
    { city: "Lisbon", country: "Portugal", code: "LIS", timezone: "Europe/Lisbon" },
    { city: "Moscow", country: "Russia", code: "SVO", timezone: "Europe/Moscow" },
    { city: "Saint Petersburg", country: "Russia", code: "LED", timezone: "Europe/Moscow" },
    { city: "Istanbul", country: "Turkey", code: "IST", timezone: "Europe/Istanbul" },

    // Asia
    { city: "Tokyo", country: "Japan", code: "HND", timezone: "Asia/Tokyo" },
    { city: "Osaka", country: "Japan", code: "KIX", timezone: "Asia/Tokyo" },
    { city: "Kyoto", country: "Japan", code: "UKY", timezone: "Asia/Tokyo" },
    { city: "Shanghai", country: "China", code: "PVG", timezone: "Asia/Shanghai" },
    { city: "Beijing", country: "China", code: "PEK", timezone: "Asia/Shanghai" },
    { city: "Hong Kong", country: "China", code: "HKG", timezone: "Asia/Hong_Kong" },
    { city: "Mumbai", country: "India", code: "BOM", timezone: "Asia/Kolkata" },
    { city: "Delhi", country: "India", code: "DEL", timezone: "Asia/Kolkata" },
    { city: "Bangalore", country: "India", code: "BLR", timezone: "Asia/Kolkata" },
    { city: "Kolkata", country: "India", code: "CCU", timezone: "Asia/Kolkata" },
    { city: "Chennai", country: "India", code: "MAA", timezone: "Asia/Kolkata" },
    { city: "Seoul", country: "South Korea", code: "ICN", timezone: "Asia/Seoul" },
    { city: "Jakarta", country: "Indonesia", code: "CGK", timezone: "Asia/Jakarta" },
    { city: "Bangkok", country: "Thailand", code: "BKK", timezone: "Asia/Bangkok" },
    { city: "Singapore", country: "Singapore", code: "SIN", timezone: "Asia/Singapore" },
    { city: "Kuala Lumpur", country: "Malaysia", code: "KUL", timezone: "Asia/Kuala_Lumpur" },
    { city: "Manila", country: "Philippines", code: "MNL", timezone: "Asia/Manila" },
    { city: "Ho Chi Minh City", country: "Vietnam", code: "SGN", timezone: "Asia/Ho_Chi_Minh" },
    { city: "Hanoi", country: "Vietnam", code: "HAN", timezone: "Asia/Ho_Chi_Minh" },
    { city: "Taipei", country: "Taiwan", code: "TPE", timezone: "Asia/Taipei" },
    { city: "Dubai", country: "UAE", code: "DXB", timezone: "Asia/Dubai" },
    { city: "Abu Dhabi", country: "UAE", code: "AUH", timezone: "Asia/Dubai" },
    { city: "Doha", country: "Qatar", code: "DOH", timezone: "Asia/Qatar" },
    { city: "Riyadh", country: "Saudi Arabia", code: "RUH", timezone: "Asia/Riyadh" },
    { city: "Jeddah", country: "Saudi Arabia", code: "JED", timezone: "Asia/Riyadh" },
    { city: "Tel Aviv", country: "Israel", code: "TLV", timezone: "Asia/Jerusalem" },

    // Africa
    { city: "Cairo", country: "Egypt", code: "CAI", timezone: "Africa/Cairo" },
    { city: "Lagos", country: "Nigeria", code: "LOS", timezone: "Africa/Lagos" },
    { city: "Johannesburg", country: "South Africa", code: "JNB", timezone: "Africa/Johannesburg" },
    { city: "Cape Town", country: "South Africa", code: "CPT", timezone: "Africa/Johannesburg" },
    { city: "Nairobi", country: "Kenya", code: "NBO", timezone: "Africa/Nairobi" },
    { city: "Addis Ababa", country: "Ethiopia", code: "ADD", timezone: "Africa/Addis_Ababa" },
    { city: "Casablanca", country: "Morocco", code: "CMN", timezone: "Africa/Casablanca" },

    // Oceania
    { city: "Sydney", country: "Australia", code: "SYD", timezone: "Australia/Sydney" },
    { city: "Melbourne", country: "Australia", code: "MEL", timezone: "Australia/Melbourne" },
    { city: "Brisbane", country: "Australia", code: "BNE", timezone: "Australia/Brisbane" },
    { city: "Perth", country: "Australia", code: "PER", timezone: "Australia/Perth" },
    { city: "Adelaide", country: "Australia", code: "ADL", timezone: "Australia/Adelaide" },
    { city: "Auckland", country: "New Zealand", code: "AKL", timezone: "Pacific/Auckland" },
    { city: "Wellington", country: "New Zealand", code: "WLG", timezone: "Pacific/Auckland" },
    { city: "Christchurch", country: "New Zealand", code: "CHC", timezone: "Pacific/Auckland" },
];
